### ISSUE TITLE
bower.json small bug

### ISSUE THREAD

**Issue by omri-shaiko** [facultymatt/angular-unsavedChanges#16]
You have small bug in bower.json.

You need to change it from:

```
"main": "unsavedChanges.js",
```

To

```
"main": "dist/unsavedChanges.js",
```

**Comment by amotamed** [comment]
- can we get this resolved soon?

**Comment by sfakir** [comment]
same here! Please fix this bug! thank you

**Comment by ricn** [comment]
I'm having the same problem.
