### ISSUE TITLE
Update with fix for multiple forms

### ISSUE THREAD

**Issue by facultymatt** [facultymatt/angular-unsavedChanges#2]
Just a reminder, we need to update this to our recent version which supports multiple forms and a clear button. 

See https://github.com/facultymatt/angular-unsavedChanges/issues/1

**Comment by devorbitus** [comment]
I would love to see the recent version.

**Comment by facultymatt** [comment]
@devorbitus Check out https://github.com/facultymatt/angular-unsavedChanges/tree/develop. I just pushed an update with a working demo.

**Comment by devorbitus** [comment]
This is awesome, thanks so much. If you find the time, it would be awesome if it was in the bower registry for easy installation.

Edit: Nevermind, I now see it was added to the registry

**Comment by facultymatt** [comment]
It's all setup to be on bower, I'm waiting to clean up a few loose ends before officially releasing it. Mainly I don't think it should be necessary to wrap everything in a group. Also, I'd like to resolve the scope issues first.
