### ISSUE TITLE
Issue with Isolate scope directive disallowing the use of other directives on form element.

### ISSUE THREAD

**Issue by wawyed** [facultymatt/angular-unsavedChanges#22]
In 0.2+ there was introduced the use of isolate scope in unsavedChangesForm directive. This makes impossible for other directives that create child scopes to work in the same element as the form directive. 
Do you actually need to create an scope at all for the directive, seems rather unnecessary. If you do require to isolate the scope could you at least make the directive require the form controller at parent level as well as element ( as in require: '^form') so we can move the unsavedChangesForm directive to a stand alone element inside a form.

**Comment by wawyed** [comment]
Could you have a look at this please? It's the only thing that prevents me from updating to the new version with all the bugs fixed. Would you like me to commit a PR with the fix?

**Comment by facultymatt** [comment]
Check it out, should be fixed now in

_0.2.3-alpha.2_

On Mon, Nov 3, 2014 at 4:32 AM, wawyed notifications@github.com wrote:

> Could you have a look at this please? It's the only thing that prevents me
> from updating to the new version with all the bugs fixed. Would you like me
> to commit a PR with the fix?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/facultymatt/angular-unsavedChanges/issues/22#issuecomment-61454952
> .

## 

Matt Miller

Web Master
609-335-4417
matt@superpedestrian.com
https://www.superpedestrian.com/
https://www.google.com/url?q=https%3A%2F%2Fwww.superpedestrian.com%2F&sa=D&sntz=1&usg=AFQjCNHLEDFaMLgggeXL8rh4gGlNfN0WSA

---

Superpedestrian Inc.
84 Hamilton St.
Cambridge, MA 02139

_This message is intended only for the addressee named above.  If you are
not the intended recipient of this message, you are hereby notified that
you must not use, disseminate, or copy it in any form or take any action in
reliance upon it.  If you have received this message in error, please
delete it and any copies of it from your email system and reply immediately
to the sender at the address shown above.  This message may contain
confidential and/or proprietary information.  Neither confidentiality, nor
any proprietary rights are intended to be waived or lost by any error in
transmission._

**Comment by wawyed** [comment]
Thank you :)

**Comment by facultymatt** [comment]
Make sure to use `v0.2.3-alpha.3` which fixes a nasty bug with the previous iteration.
