### ISSUE TITLE
Are there any examples for using this with Angular Translate?

### ISSUE THREAD

**Issue by danielcrisp** [facultymatt/angular-unsavedChanges#45]
It seems `useTranslateService` is disabled in the demo.

I'm having trouble getting it working, so I just wanted to see a working example.

I've added the strings to my translations but I keep seeing `[object Object]`

``` javascript
        $translateProvider.translations('en', {
            LOADING: 'Loading',

            reloadMessage: 'Reload message',
            navigateMessage: 'Navigate message'
        });
```

Probably I've got a problem somewhere else though...

I'm using this as my translation engine: https://angular-translate.github.io/

**Comment by danielcrisp** [comment]
Ok figured it out, should have read the docs properly

Anyway here is a plnkr that shows it in use with:
- Angular Translate
- Angular UI Router

http://embed.plnkr.co/GUeQfBWl4KMOfxXN3doR/preview

**Comment by Stargator** [comment]
Thanks @danielcrisp
