### ISSUE TITLE
Warning alert shows up twice

### ISSUE THREAD

**Issue by coonsa2** [facultymatt/angular-unsavedChanges#58]
The alert dialog box appears again after clicking ok to say you're okay with leaving these changes behind. Here's what I'm using on the form tag, I'm not sure why it shows up twice

  <form ng-model="$scope.genre" unsaved-warning-form>

**Comment by gkTim** [comment]
I also have the problem that the message appears twice.
I've added `unsaved-warning-form` to the form tag.

**Comment by Stargator** [comment]
@coonsa2 I don't see any code snippet. If we could see how you are using it it will be good. Also, remember that if you have a form within a form and they both have unsaved-warning-form, then it will cause a double pop-up.

**Comment by coonsa2** [comment]
@Stargator I should have closed this a while ago. I believe this was the problem at the time, so anyone else experiencing the double popup should look at that first. Thanks!

**Comment by sureshkoduri** [comment]
Hi, I only one form but the popup coming twice. Please help me

**Comment by Stargator** [comment]
@sureshkoduri Can you post a link to a JSFiddle or working example of your code? So I can see what might be the problem.

**Comment by PriyaS1501** [comment]
The alert dialog box appears again after clicking ok. Here's what I'm using on the login form tag, I'm not sure why it shows up twice.
